Refactor: avoid warning triggering construct with GCC8
lrm.c: In function ‘unescape_newlines’:
lrm.c:2387:9: error: ‘strncpy’ output truncated before terminating
                     nul copying 2 bytes from a string of the same
                     length [-Werror=stringop-truncation]
         strncpy(pch, "\n ", 2);
         ^~~~~~~~~~~~~~~~~~~~~~

It was actually purposeful here, so switch to less worrying memcpy
instead (deemed better alternative to stepwise indexed assignments).

Possibly relevant:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81117#c9