Low: controller: address format-overflow warnings
When using -O3 to build pacemaker, gcc (14) will throw format-overflow
warnings for some possibly null '%s' directive arguments. While we could
address the current instance of such warning by introducing checks for
null pointers, let's just remove this log entry here since it is not
meaningful.

alerts.c:153:19: error: '%s' directive argument is null [-Werror=format-overflow=]
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
    |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alerts.c:153:46: note: format string is defined here
153 |         crm_trace("Inserting alert key %s = '%s'", *key, value);
    |

Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>