Build: Fix for -Werror build (s/g_main_new/g_main_loop_new/)
They have a broken g_main_new() macro definition that inclues the
trailing semicolon, which then breaks with
crm_node.c:348: error: ISO C90 forbids mixed declarations and code