Build: lrmd: Include libxml/tree.h in lrmd.h
65d0b80 introduced "xmlNode *versioned_params" in lrmd_event_data_t but
without including libxml/tree.h in lrmd.h.

Sbd failed to build against it:

In file included from /usr/include/pacemaker/crm/common/util.h:33:0,
                 from sbd-inquisitor.c:19:
/usr/include/pacemaker/crm/lrmd.h:241:5: error: unknown type name ‘xmlNode’
     xmlNode *versioned_params;
     ^