Med: doc: fix unability to build CFS on Fedora 22
Publican was tripping over duplicate ID:

> FATAL ERROR: validity:513 in Clusters_from_Scratch.xml on line 6:
> ID pref-Clusters_from_Scratch-Preface already defined
> at /bin/publican line 1223.

and simply removing it does not seem to hurt anything, hence do so.

For the record, following packages might be involved (versions reflect
the upgrade from Fedora 21):
  docbook-dtds-1.0-63.fc21.noarch
  docbook-style-xsl-1.78.1-3.fc21.noarch
  publican-4.2.6-0.fc21.noarch

Alternatively, XIncluding Common_Content/Feedback.xml right way (instead
of trying Feedback.xml first and then falling back) in the same
Preface.xml appears to be helpful, too.

Signed-off-by: Jan Pokorný <jpokorny@redhat.com>