Refactor: libcib: Drop redundant setting of *answer to NULL
It's always NULL when these functions are called. Additionally, the only
callers are cib_perform_op() and cib__perform_query(), with one
exception: cib_apply_patch_event() calls cib__process_apply_patch().
cib_apply_patch_event() is unused internally but is used by sbd. It
passes NULL to cib__process_apply_patch().

Signed-off-by: Reid Wahl <nrwahl@protonmail.com>